### ISSUE TITLE
Nice job !

### ISSUE THREAD

**Issue by adevinwild** [parthx9/FindHacks#1]
I saw that you removed the topic that I commented on reddit.
Decided to let you a comment here , nice work. I like the simple design, and it works very well !

**Comment by zinader** [comment]
> I saw that you removed the topic that I commented on reddit.
> Decided to let you a comment here , nice work. I like the simple design, and it works very well !

Really sorry for that!! Thanks for the kind words and contributing to our project! Really means a lot.

![bitmoji](https://sdk.bitmoji.com/render/panel/b0cf8880-9dc5-4fcc-b3f6-d65347fa3436-9794c63e-7f8e-4b13-871b-97ab70acc373-v1.png?transparent=1&palette=1&width=246)
