### ISSUE TITLE
Suggestion - Only weekend checkbox

### ISSUE THREAD

**Issue by 00MB** [parthx9/FindHacks#8]
Nice project, I run a small hackathon community and was using a notion site to publish monthly hackathons. I like your web scraping approach, pretty cool.

Would be great if you could add a "weekend only" checkbox to your form to differentiate between the month-long and weekend events. I would do it myself but it seems like you are actively working on this so I don't want to throw in any spanners (also not the best with react).

Great project, I will share!

**Comment by 00MB** [comment]
Btw feel free to join the community as you clearly like hackathons: https://discord.gg/UQBybs4X8H

**Comment by 00MB** [comment]
Should also add the "flask" venv to the gitignore, you stated this in the setup part of your readme

**Comment by zinader** [comment]
> Nice project, I run a small hackathon community and was using a notion site to publish monthly hackathons. I like your web scraping approach, pretty cool.
> 
> Would be great if you could add a "weekend only" checkbox to your form to differentiate between the month-long and weekend events. I would do it myself but it seems like you are actively working on this so I don't want to throw in any spanners (also not the best with react).
> 
> Great project, I will share!

Thanks for that OOMB!! Really means a lot. I would definitely checkout your project and we're still working on making a better filter for the data but definitely that's good advice! If you're not good with React that's totally fine, we're all learning here! Feel free to contribute.
